version: '3.8'
services:
  ReactUI:
    build:
      context: ./ReactUI
      dockerfile: Dockerfile
    image: image_ui  
    env_file: 
      - ./ReactUI/.env
    container_name: container_ui
    ports:
      - 3000:8081
    networks:
      - my-network-name
  MLendPoint:
    build:
      context: ./MLendPoint
      dockerfile: Dockerfile
    image: image_ml  
    env_file: 
      - ./MLendPoint/src/.env
    container_name: container_ml
    ports:
      - 8080:8080
    networks:
      - my-network-name      
  CONVERTER_SERVICE:
    build:
      context: ./CONVERTER_SERVICE
      dockerfile: Dockerfile
    image: converter_image
    env_file: 
      - ./.env
    container_name: converter_container
    ports:
      - 4000:4000
    links: 
      - mongo_db
    networks:
      - my-network-name 
  mongo_db:
    image: mongo:latest
    volumes:
      - ./db:/data
    ports:
      - "27018:27017"
    networks: 
      - my-network-name
networks:
  my-network-name: