version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"

  dataBaseMongo:
    container_name: dataBaseMongo
    image: mongo
    ports: 
        - "27018:27017"
    logging: 
        driver: none
