version: "3"

services:
  mongo_db:
    image: mongo:latest
    volumes:
      - ./db:/data
    ports:
      - "27018:27017"

  backup_db:
    image: intersoftlab/mongodb-backup
    environment:
      - MONGODB_HOST=mongo_db
      - MONGODB_PORT=27017
      - MAX_BACKUPS=30
      - INIT_BACKUP=true
    volumes:
      - ./backups:/backups
