export enum Code{
    EXTRACTOR_ERROR_01,
    EXTRACTOR_ERROR_02,
    EXTRACTOR_ERROR_03,
    EXTRACTOR_ERROR_04,
    EXTRACTOR_ERROR_05,
    EXTRACTOR_ERROR_06,
    EXTRACTOR_ERROR_07,
    EXTRACTOR_ERROR_08,
    EXTRACTOR_ERROR_09,
    EXTRACTOR_ERROR_10
}
