const apolloCode = {
    APOLLO_ERROR_01: "APOLLO_ERROR_01",
    APOLLO_ERROR_02: "APOLLO_ERROR_02",
    APOLLO_ERROR_03: "APOLLO_ERROR_03",
    APOLLO_ERROR_04: "APOLLO_ERROR_04",
    APOLLO_ERROR_05: "APOLLO_ERROR_05",
    APOLLO_ERROR_06: "APOLLO_ERROR_06",
    APOLLO_ERROR_07: "APOLLO_ERROR_07",
    APOLLO_ERROR_08: "APOLLO_ERROR_08",
    APOLLO_ERROR_09: "APOLLO_ERROR_09",
    APOLLO_ERROR_10: "APOLLO_ERROR_10"
};

export default apolloCode;
